spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  datasource-common:
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
  master-datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://sh-pl-datamgt01.wmcloud-dev.com:3306/monitor?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: njadmin
      password: njadmin@123
log:
  path: /toy/logs
server:
  port: 9999

#swagger开启
swagger
  enble: true
